#!/usr/bin/env python3
#
# Writes the attribution notice for everything compiled into the service binary,
# to stdout.
#
#   ./licenses.py > THIRD-PARTY.md      regenerate the checked-in notice
#
# Every permissive licence in the tree — MIT, BSD, Apache-2.0 — asks the same
# thing of a binary: that the copyright line and the permission text travel with
# it. An SPDX identifier is not that text, so this collects the real files rather
# than listing names, and reads them from the crates already unpacked in the
# cargo registry rather than fetching anything.
#
# The vendored parts of the viewer are here too. They are compiled into the same
# binary by `include_str!` and are owed the same notice as anything from crates.io.
#
# Run it again whenever a dependency is added, removed, or moved.

import json
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent

# Named files rather than a glob, so that a stray LICENSE.spdx or an unrelated
# COPYING.md in a crate's root cannot silently become the notice this reproduces.
LICENCE_FILES = ("LICENSE", "LICENCE", "COPYING", "NOTICE", "UNLICENSE")

# What is vendored under `src/vendor`, in the order it is reported. A table
# rather than a branch each, so that adding the next one is a line here and the
# missing-licence path is written once — a vendored thing whose notice has gone
# astray is the one case that must stop the run rather than quietly shorten it.
#
# Only the marks named in `src/chrome.rs` are compiled in, but the notice is owed
# on the whole of what the repository carries: the licence travels with the copy,
# and the copy here is the whole pack.
VENDORED = (
    (
        "leaflet 1.9.4",
        "leaflet-LICENSE",
        "Vendored in `src/vendor` and compiled into the binary. BSD-2-Clause.",
        "https://github.com/Leaflet/Leaflet",
    ),
    (
        "phosphor-icons 2.1.1",
        "phosphor-LICENSE",
        "Vendored in `src/vendor/phosphor`; the marks the viewer wears are "
        "compiled into the binary. MIT.",
        "https://github.com/phosphor-icons/core",
    ),
)


def crates():
    """Every crate whose code reaches the binary, nearest the root first."""
    raw = subprocess.run(
        ["cargo", "metadata", "--format-version", "1"],
        cwd=HERE, check=True, capture_output=True, text=True,
    ).stdout
    meta = json.loads(raw)

    packages = {p["id"]: p for p in meta["packages"]}
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
    root = meta["resolve"]["root"]

    # Normal dependencies only. A build script or a proc macro runs at compile
    # time and leaves nothing of itself behind, so attributing it would claim the
    # binary carries code that it does not.
    seen, stack = set(), [root]
    while stack:
        current = stack.pop()
        if current in seen:
            continue
        seen.add(current)
        for dep in nodes[current]["deps"]:
            if any(kind.get("kind") is None for kind in dep["dep_kinds"]):
                stack.append(dep["pkg"])

    seen.discard(root)
    return sorted((packages[i] for i in seen), key=lambda p: p["name"].lower())


def texts(package):
    """The licence files a crate ships, as (name, text)."""
    root = pathlib.Path(package["manifest_path"]).parent
    found = []
    for path in sorted(root.iterdir()):
        if not path.is_file():
            continue
        stem = path.name.split(".")[0].split("-")[0].upper()
        if stem in LICENCE_FILES:
            found.append((path.name, path.read_text(encoding="utf-8", errors="replace")))
    return found


def block(title, subtitle, entries, upstream):
    print(f"## {title}\n")
    print(f"{subtitle}  ")
    print(f"<{upstream}>\n")
    if not entries:
        # Said rather than skipped: a crate that ships no licence text is the one
        # case a reader has to resolve by hand, and a silent gap reads as nothing
        # being owed.
        print("This crate ships no licence text of its own. The terms are the SPDX")
        print("identifier above, as published; the text is at the upstream link.\n")
        return
    for name, text in entries:
        print(f"### {name}\n")
        print("```")
        print(text.strip())
        print("```\n")


def main():
    print("# Third-party notices\n")
    print("Everything compiled into the `witchlight` binary that somebody else wrote,")
    print("with the notice each one asks to travel with a copy. Generated by")
    print("`./licenses.py`; regenerate it whenever a dependency changes.\n")
    print("Nothing here places a condition on witchlight's own terms, which are MIT")
    print("and in `LICENSE`. One entry is weak copyleft and is called out where it")
    print("appears.\n")
    print("---\n")

    vendor = HERE / "src" / "vendor"
    missing = False
    for title, licence, subtitle, upstream in VENDORED:
        path = vendor / licence
        if not path.exists():
            print(f"licenses: {path} is missing", file=sys.stderr)
            missing = True
            continue
        block(title, subtitle, [(path.name, path.read_text(encoding="utf-8"))], upstream)
        print("---\n")
    if missing:
        return 1

    for package in crates():
        subtitle = f"{package['version']} — {package.get('license') or 'no SPDX identifier published'}"
        upstream = (
            package.get("repository")
            or package.get("homepage")
            or f"https://crates.io/crates/{package['name']}"
        )
        block(package["name"], subtitle, texts(package), upstream)

    return 0


if __name__ == "__main__":
    sys.exit(main())
